name: Publish NPM Module

on:
  push:
    branches: [ main, master ]

jobs: 
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

  publish-npm:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: node --version
      - run: npm --version
      - run: npm ci
      - name: "Install local extension"
        run: gh extension install .
      - name: "View extensions"
        run: gh extension list
      - name: "Run Mocha and Chai tests"
        run: npm test
        env: 
          CI: true 
