name: Publish NPM Module

on:
  push:
    branches: [ main, master ]

jobs: 
  publish-npm:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: 'https://registry.npmjs.org'
          scope: "@alu0101106335"

      - name: "Install dependencies" 
        run: npm ci

      - name: "Install local extension"
        run: gh extension install .
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: "Run Mocha and Chai tests"
        run: npm test
        env: 
          CI: true 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}


  # If module is published create an issue to execute production tests in testing-gh-issues
  create-issue:
    needs: publish-npm
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # When published warns testing repository to execute the production tests
      - name: "Comment issue in testing-gh-issue"
        run: gh issue create --repo ULL-MII-SYTWS-2122/testing-gh-issues --label publish-npm --title "Package new version published in NPM" --body ""
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          ISSUE: ${{ secrets.TESTING_GH_ISSUES_ISSUES_URL }}

